<?php
$title = "qrcore";
$summary = "Prototyping a possible future for lottery games";
$year = 2015;

$content = array(array("132325021", "col-10 left-1 video"),
				 array("Qrcore is a design fiction project exploring near future uses for mobile cameras. We produced a video depicting a future where qr codes are not generated by machines anymore. Embedded inside scratch cards, they become part of a new perspective for lottery and gambling games, involving social networks upgrades and police tickets quotas betting. Scratch cards are played with smartphones, while the players, blinded by the encoding technique of the qr codes they don’t know, try to generate them correctly and validate them with their cameras.","col-8 left-2 top-2 bot-3"),
				 array("qrcore01.jpg","col-6 image"),
				 array("qrcore02.jpg","col-6 image"),
				 array("qrcore03.jpg","col-6 image"),
				 array("qrcore04.jpg","col-6 image"),
				 array("qrcore05.jpg","col-6 image"),
				 array("qrcore06.jpg","col-6 image"),
				 array("qrcore08.jpg","col-8 left-2 top-3 image"),
				 array("Transcripts from a few interviews we did. Here, one of our subjects, a 10 year old boy, explains using qr codes as a way to cheat in Pokémon with his 3DS.","col-2 left-0 top-3 bot-0"),
				 array("qrcore07.jpg","col-7 left-0 top-1 image"),
				 array("Some of the props for future lottery games built during the project.","col-3 left-0 top-1 bot-0"),
				 // array("qrcore01.png","col-5 left-1 image"),
				 // array("qrcore02.png","col-5 image"),
				 // array("qrcore03.png","col-5 left-1 image"),
				 // array("qrcore04.png","col-5 image"),
				 // array("qrcore05.png","col-5 left-1 image"),
				 // array("qrcore06.png","col-5 image"),
				 array("Teamwork done with: Camille Rattoni.", "col-12 top-2 bot-1"),
				 array(a, "line")
		  );

include "../../project.php";

?>
